server:
  port: @port@
  servlet:
    context-path: /api/auth

spring:
  redis:
    host: @redis.host@
    port: @redis.port@
  datasource:
    url: @mysql.jdbc.url@
    username: @mysql.jdbc.username@
    password: @mysql.jdbc.password@
    driver-class-name: @driverclass@
    maxActive: 2
    initialSize: 1
  application:
    name: auth-service
  dubbo:
    server: true
    registry: multicast://224.0.0.0:1111

sys:
  name: mage
  description: test
  version: 1.0
  apipath :
  auth:
    url:
