server:
  port: @port@
  servlet:
    context-path: /api/mgr

spring:
  redis:
    host: @redis.host@
    port: @redis.port@
  datasource:
    url: @mysql.jdbc.url@
    username: @mysql.jdbc.username@
    password: @mysql.jdbc.password@
    driver-class-name: @driverclass@
    maxActive: 2
    initialSize: 1

mybatis:
  config-location: classpath:/mybatis-config.xml

sys:
  name: mage
  description: test
  version: 1.0
  apipath : com.ice.tech.gh.managersite.app.controller
  auth:
    url: /**
