version: '3'
services:
  eureka:
    image: cloud/eurekaserver
    ports:
      - "8761:8761"
    networks:
      springcloud-overlay:
        aliases:
          - eureka
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
